# Generated by Django 4.2.7 on 2026-03-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_auditlog_accion_alter_auditlog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tardanzas_alerta_limite', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del sistema',
                'verbose_name_plural': 'Configuracion del sistema',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AlertaTardanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(db_index=True, help_text='Inicio de semana (lunes).')),
                ('cantidad_tardanzas', models.PositiveIntegerField(default=0)),
                ('resuelta', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tardanza', to='control.empleado')),
            ],
            options={
                'verbose_name': 'Alerta de tardanza',
                'verbose_name_plural': 'Alertas de tardanza',
                'db_table': 'alerta_tardanza',
                'ordering': ['resuelta', '-cantidad_tardanzas', '-semana', 'empleado__apellido', 'empleado__nombre'],
                'indexes': [models.Index(fields=['resuelta', 'cantidad_tardanzas'], name='alerta_resuelta_cant_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='alertatardanza',
            constraint=models.UniqueConstraint(fields=('empleado', 'semana'), name='alerta_tardanza_emp_semana_uniq'),
        ),
    ]
